[package]
name = "rust-elm-example"
version = "0.1.0"
authors = ["Clemens Wallrath <dev@nervengiftlabs.de>"]
build = "build.rs"

[dependencies]
iron = "0.4"
mount = "0.2"
router = "0.2"
staticfile = "0.3"
